name: verify TIFS

on:
    #
  
    # Allow to run this workflow manually from the Actions tab
    workflow_dispatch:
  
jobs:
    # job 1
    verify_tifs:
        runs-on: self-hosted

        steps:
           - name: step 1
             run: |
                /home/ying-cai/Workspace/ble_auto_testing/venv/bin/python /home/ying-cai/Workspace/ble_auto_testing/ble_auto_testing.py --interface /dev/ttyACM0-None --device "" --brd0-addr 00:11:22:33:44:11 --brd1-addr 00:11:22:33:44:12 --sp0 /dev/ttyUSB1 --sp1 /dev/ttyUSB3 --time 30 --tshark /usr/bin/tshark  
           
  
